import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { generateMockDataset } from "../integrations/denticon/mock/data.js";

// `npm run denticon:samples` — writes one example payload per endpoint to
// docs/samples/denticon/ so the shapes can be read without running anything. Pinned to a
// fixed reference date so the output is stable across runs (commit the result).

const outDir = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "../../../docs/samples/denticon");
const data = generateMockDataset({ referenceDate: new Date("2026-09-15T12:00:00Z"), seed: 20260916 });

const page = <T>(rows: T[], n: number, totalCount = rows.length) => ({
  data: rows.slice(0, n),
  message: "Success",
  pageNumber: 1,
  pageSize: n,
  pageCount: Math.min(n, rows.length),
  totalCount,
  totalPages: Math.max(1, Math.ceil(totalCount / n)),
});
const single = <T>(row: T) => ({ data: row, message: "Success" });

// Pick a patient with a multi-item accepted plan so the interesting fields are populated.
const richPlanId = [...new Set(data.treatmentPlanItems.filter((i) => i.treatPlanStatus === "A" && i.isCompleted).map((i) => i.treatPlanId))][0]!;
const richPatientId = data.treatmentPlanItems.find((i) => i.treatPlanId === richPlanId)!.patientId;
const richPatient = data.patients.find((p) => p.patientId === richPatientId)!;

const files: Record<string, unknown> = {
  "GET practices-v0.json": single(data.practice),
  "GET practices-v0 offices.json": page(data.offices, 50),
  "GET practices-v0 providers.json": page(data.providers, 50),
  "GET practices-v0 referral-types.json": page(data.referralTypes, 50),
  "GET practices-v0 patient-type-codes.json": single(data.patientTypeCodes),
  "GET practices-v0 procedure-codes.json": page(data.procedureCodes, 50),
  "GET patients-v0 (list, OfficeId + LastChangedOn).json": page(
    data.patients.filter((p) => p.officeId === 101).slice(0, 3),
    3,
    data.patients.filter((p) => p.officeId === 101).length,
  ),
  "GET patients-v0 {PatientId}.json": single(richPatient),
  "GET clinical-v0 treatment-plans (list, OfficeId + LastChangedOn).json": page(
    data.treatmentPlanItems.filter((i) => i.treatPlanId === richPlanId).map(({ ucrFee: _u, ...r }) => r),
    50,
  ),
  "GET clinical-v0 patients {PatientId} treatment-plans.json": single(
    data.treatmentPlanItems.filter((i) => i.patientId === richPatientId),
  ),
  "GET appointments-v0 (list, OfficeId + AppointmentDate).json": page(
    data.appointments.filter((a) => a.patientId === richPatientId),
    50,
  ),
  "ERROR 400 problem-details.json": {
    type: "https://tools.ietf.org/html/rfc9110#section-15.5.1",
    title: "Bad Request",
    status: 400,
    detail: "LastChangedOn: the date range must not exceed 30 days.",
    instance: "/denticon/patients/v0",
    traceId: "0HN3VARQ3BHUO:00000001",
  },
  "ERROR 401 missing-key.json": {
    statusCode: 401,
    message: "Access denied due to missing subscription key. Make sure to include subscription key when making requests to an API.",
  },
  "ERROR 429 rate-limit.json": { message: "Rate limit is exceeded. Try again in 42 seconds.", statusCode: 429 },
};

await mkdir(outDir, { recursive: true });
for (const [name, body] of Object.entries(files)) {
  await writeFile(path.join(outDir, name), JSON.stringify(body, null, 2) + "\n");
}
await writeFile(
  path.join(outDir, "README.md"),
  `# Denticon API sample payloads

Synthetic example responses in the exact shapes documented for the PlanetDDS / Denticon
v0 REST API (https://developer.planetdds.com/apis). Generated by
\`npm run denticon:samples\` from \`backend/src/integrations/denticon/mock/data.ts\` —
edit the generator, not these files. Every name, phone, email and address is invented.

File names are \`<METHOD> <area>-<version> <path> (<notes>).json\`. Base URL for all of
them is \`https://api.planetdds.com/denticon/\`, auth header \`PDDS-Subscription-Key\`.

Same data is served live by \`npm run denticon:mock\` — see docs/denticon-api.md.

Dataset (seed 20260916, reference date 2026-09-15): ${data.offices.length} offices,
${data.providers.length} providers, ${data.patients.length} patients,
${new Set(data.treatmentPlanItems.map((i) => i.treatPlanId)).size} treatment plans
(${data.treatmentPlanItems.length} procedure items), ${data.appointments.length} appointments.
`,
);
console.log(`wrote ${Object.keys(files).length + 1} files to ${outDir}`);
